### ISSUE TITLE
Controller session

### ISSUE THREAD

**Issue by huesitos** [huesitos/aplus#19]
Test:
* create
  * with existing user
  * with non-existing user
* destroy

**Comment by gotjosh** [comment]
Hey there! I'm about to start working on this one, is it ok if I do some refactoring along the way?

**Comment by huesitos** [comment]
Hello! Sure!

**Comment by gotjosh** [comment]
@huesitos right now the app allows you the log in via Facebook, Twitter and Google. Could you please create sandbox applications in each platform in order to leave those as "defaults" so that the app just works out of the box.

**Comment by huesitos** [comment]
@gotjosh I don't want to commit the omniauth file with the sandbox apps' keys embedded in it. If I list them in the readme file, would that be good for you?

**Comment by gotjosh** [comment]
For me, it makes no difference. The idea behind it is that whenever someone wants to work on the app or contribute, they don't have to go through the process of having to create these apps in the corresponding Platform, it can very tedious specially if you don't have an account for that specific platform.
