### ISSUE TITLE
Add color picker to subject form

### ISSUE THREAD

**Issue by huesitos** [huesitos/aplus#25]
Instead of asking for a hex color, let the user pick it with a color picker.

**Comment by marti700** [comment]
I did this. You can check it out (guess where) in the color-picker brach

**Comment by huesitos** [comment]
Neat. Now that I think about it, it would be awesome if we could show how the subject tag will look like. Taking the code and the color, add a little demonstration below the color picker. Just the same tag that appears in the menu when a topic has a subject.

**Comment by marti700** [comment]
It's Done! the preview looks like the ones that appear in review/study_calendar by the side of the topics. I hope that was what you meant with " Just the same tag that appears in the menu when a topic has a subject" and if not let me know and I'll fix it.

**Comment by huesitos** [comment]
Yes, sir. Ty
