### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by gotjosh** [huesitos/aplus#35]
One way to guarantee integrity of the project is to have a CI platform (such as [travis](https://travis-ci.org/) or [CodeShip](https://codeship.com/)) post back to Github in order to know if the Pull Request or Commit passed the tests, this is important for open source projects where other users which might not know all the details of an application could make breaking changes.

I suggest you add these ASAP in order to minimize Regressions.

EDIT: I forgot to mention that both platforms are free for Open Source projects.

**Comment by huesitos** [comment]
There is one: https://travis-ci.org/huesitos/aplus
We just haven't finished the tests yet, so it'll be failing till we finish them. But there is this issue https://github.com/huesitos/aplus/issues/34, that we don't know how to solve yet.

**Comment by gotjosh** [comment]
Could you please integrate it with github so that it reports back via the Pull Requests?

**Comment by huesitos** [comment]
I think it does now. Isn’t the x next to the pull-requests signalling it failed CI tests in https://github.com/huesitos/aplus/pulls?q=is%3Apr+is%3Aclosed?

**Comment by huesitos** [comment]
Like I said in the previous comment, this is already done. I'm closing it.
