### ISSUE TITLE
Beautify error messages in forms

### ISSUE THREAD

**Issue by huesitos** [huesitos/aplus#6]
Make them something like Twitter bootstrap style.

**Comment by francisbrito** [comment]
What do you think about these?

![error-scrot](https://cloud.githubusercontent.com/assets/2180822/7899696/472dfe70-06fc-11e5-8cdc-cbd592678ba0.png)

**Comment by huesitos** [comment]
Pretty neat.

**Comment by francisbrito** [comment]
Then check-out #10
